### ISSUE TITLE
Pass path data to native code as serialized JSON string, not FFI arguments

### ISSUE THREAD

**Issue by shueja** [SleipnirGroup/Choreo#100]
This enables more flexibility and less duplication of data types.

There are two main options to do this:
1. 
a. TS frontend sends path string to Tauri Rust backend through a Tauri command.
b. Rust parses it and sets up TrajoptLib through CXX bindings similar to the existing setup. 
c. TrajoptLib returns an array of samples, which Rust serialized and returns as the command response.
2. Same as 1 but Rust directly forwards the string to be parsed by TrajoptLib, negating the need for individual bindings.

**Comment by jlbabilino** [comment]
I think 1 is essentially the same as the current setup, so it wouldn’t add much benefit. I’m in favor of 2.
