### ISSUE TITLE
CLI and GUI generate files with slight differences

### ISSUE THREAD

**Issue by pjreiniger** [SleipnirGroup/Choreo#1006]
I was hoping to make a CI action to run the CLI generation and compare it against what was checked in our repo. We had a couple instances last year of people forgetting to hit the generate button, or generating with an older version of the GUI.

However, there are super small differences between what gets written when you hit the button in the gui, and run cli. WIthout having determinism between the two tools this CI checking idea is not going to work well. I have attached a diff of one of our files. 

This happens with beta6 while running with `--chor y2024/Crescendo/src/main/deploy/choreo/ChoreoAutos.chor --generate --all-trajectory`

[example.patch](https://github.com/user-attachments/files/18120569/example.patch)

**Comment by calcmogul** [comment]
Interesting, the difference is in the last sigfig:
```diff
diff --git a/old.traj b/new.traj
index 67c1eef..3cbd12c 100644
--- a/old.traj
+++ b/new.traj
@@ -6,7 +6,7 @@
   "vx":0.0,
   "vy":0.0,
   "omega":0.0,
-  "ax":9.015400166238956,
+  "ax":9.015400166238955,
   "ay":0.3234650217519276,
   "alpha":0.0,
   "fx":[153.34937729635206,153.34937729635206,153.34937729635206,153.34937729635206],
```
