### ISSUE TITLE
Add keybinds

### ISSUE THREAD

**Issue by jlbabilino** [SleipnirGroup/Choreo#102]
Keybinds for the most used parts of the UI:
* The generate button
* Showing and hiding the grid, field, etc.
* Saving, exporting, opening files
* Playing and pausing the animation

**Comment by shueja-personal** [comment]
https://tauri.app/v1/api/js/globalshortcut/

**Comment by shueja-personal** [comment]
Suggestions: 
Play/pause animation: Space
Generate: ctrl-G
Save/save-as/open: ctrl-s/ctrl-shift-s/ctrl-o
Undo-redo: ctrl-z/ctrl-y
Prev/next waypoint (or last/first if no point selected): ctrl-left arrow, ctrl-right arrow
Various key binds for selecting navbar options

**Comment by jlbabilino** [comment]
Also `ctrl-shift-z` for redo.
