### ISSUE TITLE
Differential sample flipping logic wrong

### ISSUE THREAD

**Issue by shueja** [SleipnirGroup/Choreo#1021]
It should be:
Rotate Around:
t -> t
x -> flip(x)
y -> flip(y)
heading -> heading + pi
vl,vr,omega,al,ar,fl,fr all unchanged

Mirror
x -> flip(x)
y -> y
heading -> Pi - heading
vl ->vr
vr ->vl
omega -> -omega
al -> ar
ar -> al
fl -> fr
fr -> fl

**Comment by calcmogul** [comment]
We got this wrong twice before, so we should add a unit test that checks feasibility before and after flipping/mirroring.

**Comment by shueja** [comment]
> We got this wrong twice before.
And I just got it wrong again in the initial version of this issue. This is something that would benefit from a docs page with pictures.
