### ISSUE TITLE
.traj file can't save at correct path

### ISSUE THREAD

**Issue by RockyXRQ** [SleipnirGroup/Choreo#1028]
Just install the v2025.0.0-beta-7 and rebuild a new  Choreo project, seems that it can not detect where to save the .traj file correctly.
![image](https://github.com/user-attachments/assets/73083f47-5ba8-4893-8a98-bf402c085864)

**Comment by calcmogul** [comment]
The user should save it in a deploy/choreo directory, though the docs on https://choreo.autos/usage/saving/ are out of date in that regard.
