### ISSUE TITLE
App crash with long path

### ISSUE THREAD

**Issue by Ashray-g** [SleipnirGroup/Choreo#110]
<img width="230" alt="Screenshot 2023-08-07 at 5 05 02 PM" src="https://github.com/SleipnirGroup/Choreo/assets/43589795/5adfc5cb-d232-4fe3-b328-1d63f5caa53f">
<img width="500" alt="Screenshot 2023-08-07 at 5 04 54 PM" src="https://github.com/SleipnirGroup/Choreo/assets/43589795/47583472-1c93-49eb-8658-ff17505000d1">

Path JSON:
https://pastebin.com/4UDPUzn3

<img width="158" alt="Screenshot 2023-08-07 at 5 07 10 PM" src="https://github.com/SleipnirGroup/Choreo/assets/43589795/2f2d7a40-4b14-4175-9c5c-0b3602c583e9">

Using arm release 0.2.0

**Comment by Awesomeplayer165** [comment]
from discord,

<img width="612" alt="image" src="https://github.com/SleipnirGroup/Choreo/assets/70717139/ce97dbf7-4764-4a40-aa68-108aa500efae">

**Comment by Awesomeplayer165** [comment]
for now, I decided its best to reduce the number of control intervals to around 20 or so. Click gear in your path (sidebar), uncheck guess path detail, type replace 40 with 20.

**Comment by calcmogul** [comment]
OBE by #326.
