### ISSUE TITLE
Memory leak when adding paths

### ISSUE THREAD

**Issue by shueja** [SleipnirGroup/Choreo#120]
From #115 

> Memory leak when adding paths. Added 100 paths, initially spiked to 200MB then settled down to 100. Was initially 80. I can reliably reproduce this and have gotten it to about 300MB settled after ~300 paths.

Hypothesis: is this the undo history? investigate limited-length undo history.

**Comment by spacey-sooty** [comment]
Does this still exist?

**Comment by spacey-sooty** [comment]
Can't reproduce on beta 2
