### ISSUE TITLE
Crash when removing zero velocity waypoints on generate

### ISSUE THREAD

**Issue by willtoth** [SleipnirGroup/Choreo#140]
When built for desktop and installed, I don't see this. I only see this error when running through `npm run tauri dev -- --release`

OS: Windows 11
Commit: 736145107fcf16b162ae20621deeb33a9c001c5b

**Repro Steps:**

1. Add some waypoints
2. Set the waypoint to a zero velocity constraint (or do it twice, it'll show up twice for the same point)
3. Delete the constraint
4. Press generate

**Expected Result:**

Path is generated

**Actual Result:**

Hard crash, but only in dev build apparently.

**Comment by shueja** [comment]
Closed as completed/outdated
