### ISSUE TITLE
Support command markers 

### ISSUE THREAD

**Issue by lidor51** [SleipnirGroup/Choreo#185]
Support command markers (both in FE & BE) to a full robot autonomous support.
(You can see PathPlanner implementation as a reference).

**Comment by stellaremnant** [comment]
Possible implementation could be an `Event` Waypoint constraint that takes a `String`, with `choreoSwerveCommand` taking `HashMap<String, Command>` to invoke the corresponding commands?
Empty Waypoint could be used for mid-segment events.

**Comment by calcmogul** [comment]
This is out of scope for ChoreoLib due to lack of development resources. Use https://github.com/SleipnirGroup/Choreo/pull/306 and PathPlannerLib instead.
