### ISSUE TITLE
Publish AppImage in addition to .deb on Linux

### ISSUE THREAD

**Issue by OnlyCS** [SleipnirGroup/Choreo#283]
Hey,

I'm using an x64 based linux distro but the deb file in releases will not work with my Fedora system. Any change of switching to a unified packaging system, like a flatpak, AppImage, or supporting builds for these other distributions?

For now, I will build this project from source.

Thanks for your help

**Comment by calcmogul** [comment]
Here's the docs for Tauri packaging, for reference: https://tauri.app/v1/guides/building/linux/.

Looks like the only other option is AppImage.

**Comment by OnlyCS** [comment]
welp looks like i cant build on fedora due to lack of libsoup @ 2.4 (i have 2.7.4, no 2.4.x on fedora repos)

**Comment by OnlyCS** [comment]
whoops found a fix. running an appimage here! ill make a pr
![image](https://github.com/SleipnirGroup/Choreo/assets/61358474/fb845e2f-bb3d-4695-9efd-3c4466ac5683)

**Comment by calcmogul** [comment]
Now that we link everything statically, there shouldn't be missing libraries anymore. It's worth trying again.

**Comment by OnlyCS** [comment]
ill take a look at this in a bit
