### ISSUE TITLE
[Bug] Pathing breaks with path splitting

### ISSUE THREAD

**Issue by CodeCreator3** [SleipnirGroup/Choreo#293]
When generating paths with the "split .traj files" option enabled, our path breaks. The robot appears to teleport from being part way through the first segment of the path to being part way through the second segment of the path, then when it finishes the trajectory, it just waits for the time to end. Simming these paths, it appears that this bug only affects the main [pathname].traj file and not the individual segment files that are also generated. Here's my team's .chor file that has the issue: https://drive.google.com/file/d/124qTSqWfkB5Nusha05xpGuutZ-Swp36x/view?usp=sharing

To reproduce:
1. open my team's .chor file
2. ensure that split traj files option is enabled in choreo export config
3. choose "NewPath" 
4. generate path

This is using Choreo 2024.1.2

![image](https://github.com/SleipnirGroup/Choreo/assets/92405837/83ca097e-8309-4337-a355-38935b350328)

**Comment by shueja** [comment]
Known issue, the fix will be in the next release.
