### ISSUE TITLE
Compile trajectory optimizer to webassembly

### ISSUE THREAD

**Issue by nlaverdure** [SleipnirGroup/Choreo#30]

**Comment by jlbabilino** [comment]
Now that we've switched from running the app purely on the web to a native desktop app stack, this is unnecessary.

**Comment by JoshuaAN** [comment]
We could always run the app natively through Electron (and now Tauri). It was a goal to run on the web in addition though, I don't believe this has changed.

**Comment by jlbabilino** [comment]
Understood, I’ve adjusted the labels accordingly

**Comment by shueja** [comment]
No longer planned.
