### ISSUE TITLE
Replace the dot handle on the robot UI element with a triangle

### ISSUE THREAD

**Issue by calcmogul** [SleipnirGroup/Choreo#341]
A triangle makes it clearer whether that handle is attached to the front or back of the robot.

**Comment by Nsl106** [comment]
Not sure if this issue is even still something that needs to be done, but figured I would find something easy to try to make sure I set everything up correctly :)
![image](https://github.com/SleipnirGroup/Choreo/assets/87742096/8313d2f9-c9e3-48a2-8fa5-275f67db9b0c)
