### ISSUE TITLE
Docs: Update document keyboard shortcuts

### ISSUE THREAD

**Issue by calcmogul** [SleipnirGroup/Choreo#355]
This could be a page on https://sleipnirgroup.github.io/Choreo/, an in-app dialog, or both.

**Comment by Awesomeplayer165** [comment]
Oh it should also be an in app dialog.

**Comment by calcmogul** [comment]
In-app keyboard shortcut docs is now a separate issue: https://github.com/SleipnirGroup/Choreo/issues/373

**Comment by Awesomeplayer165** [comment]
> In-app keyboard shortcut docs is now a separate issue: #373. This issue is now only concerned with the documentation website.

We currently have this: https://sleipnirgroup.github.io/Choreo/usage/controls-shortcuts/
