### ISSUE TITLE
Enhance GUI Angle Setting with Support for Constants and Units

### ISSUE THREAD

**Issue by ori-coval** [SleipnirGroup/Choreo#365]
## Description:
Currently, the GUI angle setting feature restricts users to input angles solely in Radians, lacking the flexibility to utilize mathematical constants such as π or employ alternative measurement units like degrees. 
This limitation can be cumbersome for users accustomed to degrees or those requiring precise mathematical constants in their work.

## Proposal:

Support for Mathematical Constants: Introduce support for common mathematical constants such as π. This would allow users to input angles using standard mathematical notation, enhancing usability and reducing cognitive load.

Flexibility in Measurement Units: Enable users to choose between different measurement units for angles, such as radians or degrees. This would accommodate diverse user preferences and streamline workflows for individuals accustomed to specific units.

**Comment by jlbabilino** [comment]
Related to #96

**Comment by shueja** [comment]
Duplicate of #96
