### ISSUE TITLE
"Point toward/away from point" constraint

### ISSUE THREAD

**Issue by Lewis-Seiden** [SleipnirGroup/Choreo#381]
useful for intaking and scoring where you want one end of the robot to face a game piece/goal

**Comment by shueja** [comment]
This would be extra nice when used with https://github.com/SleipnirGroup/Choreo/issues/297

**Comment by calcmogul** [comment]
This constraint could be implemented like so:
```
heading = atan2(point.y - y, point.x - x)
tan(heading) = (point.y - y)/(point.x - x)
sin(heading)/cos(heading) = (point.y - y)/(point.x - x)
sin(heading) * (point.x - x) = cos(heading) * (point.y - y)
```

**Comment by shueja** [comment]
Is there a formulation that could allow a particular error boundary around the desired heading? I expect that would make convergence easier and most uses probably don’t require exact pointing.

**Comment by calcmogul** [comment]
I'm not sure how to correctly manipulate nonlinear inequalities, so you'd probably be stuck with the following:
```
atan2(point.y - y, point.x - x) < heading + ε
atan2(point.y - y, point.x - x) > heading - ε
```
