### ISSUE TITLE
Add keyboard shortcut to open and save file

### ISSUE THREAD

**Issue by Gold872** [SleipnirGroup/Choreo#394]
When opening the app, it can be very repetitive to have to open the menu, then click open file, and then navigate to your file. It would be nice to have Ctrl + O show the open file dialog.

Alternatively, it can open the previously opened file at startup if the file still exists.

**Comment by calcmogul** [comment]
Ctrl + O to open the file dialog sounds good. CLI file open would be better for opening a file from last time.

**Comment by Awesomeplayer165** [comment]
Yes I agree with @calcmogul. `$choreo fileName.chor` would be nice

**Comment by shueja** [comment]
Ctrl-O shortcut added in #435, open last file added in #395. Closing this.
