### ISSUE TITLE
Add maximum acceleration constraint

### ISSUE THREAD

**Issue by MidgleyM** [SleipnirGroup/Choreo#421]
Having a constraint for the maximum acceleration and deceleration of your robot could help make sure that robots can follow the path better, as robots can sometimes skid if they try to decelerate or accelerate too quickly, and currently there's no real way to configure this other than having a ton of max velocity waypoints and calling it good.

**Comment by calcmogul** [comment]
A better way to solve this is a maximum force cone in the optimization problem formulation.

**Comment by calcmogul** [comment]
TrajoptLib's Rust API has `wpt_linear_acceleration_max_magnitude` and `sgmt_linear_acceleration_max_magnitude` now, so we just need to plumb it into Choreo.
