### ISSUE TITLE
Document setting "Split .traj files at stop points" erases all other paths located in the choreo paths folder as it is toggled

### ISSUE THREAD

**Issue by Maleavour** [SleipnirGroup/Choreo#424]
When I toggle the setting "Split .traj files at stop points" choreo erases all other paths I apologize for the lack of information as I new to programming and using tools like forums 

the best I can provide with my knowledge is a link to our teams code for our robot we currently use the "Y.A.G.S.L" library:

https://github.com/Deadshot222224/FRC-Code-Team-4455/tree/main/src/main/deploy/choreo

**Comment by shueja** [comment]
Closed as obsolete
