### ISSUE TITLE
Code signing on MacOS ventura still not working

### ISSUE THREAD

**Issue by qrAIhttps** [SleipnirGroup/Choreo#428]
"“Choreo-v2024.2.1-macOS-arm64.dmg” cannot be opened because it is from an unidentified developer message" appears when opening. I'm using M2 chip.

**Comment by calcmogul** [comment]
We don't know how to sign the binary (we have Tauri skip the process), and users can bypass it, as far as I know.

**Comment by qrAIhttps** [comment]
Ok. Thank you. Apple is annoying. If you did want to code sign, you would likely need to pay.
