### ISSUE TITLE
Support RPM builds in release

### ISSUE THREAD

**Issue by spacey-sooty** [SleipnirGroup/Choreo#442]
Having builds for Fedora, CentOS, RHEL etc would be a nice option

**Comment by calcmogul** [comment]
Tauri only supports .deb and .AppImage:
https://tauri.app/v1/guides/building/linux/

**Comment by calcmogul** [comment]
Tauri v2 may support RPM: https://github.com/tauri-apps/tauri/pull/5202

**Comment by spacey-sooty** [comment]
Tauri v1 appears to support RPMs see https://tauri.app/v1/api/config/#bundletype
