### ISSUE TITLE
Add "toward" and "away" options to point-at constraint

### ISSUE THREAD

**Issue by mmilunicmobile** [SleipnirGroup/Choreo#502]
This would allow teams to point with whichever side of their robot is the side they need to use. Eg: you have an intake on the back of your robot but want to point at target with the intake while intaking.

**Comment by calcmogul** [comment]
Since arbitrary offsets don't work correctly with trajectory mirroring, we should just support "toward" and "away".

**Comment by shueja** [comment]
Superseded by #565
