### ISSUE TITLE
Fix slow startup time or add a splashscreen

### ISSUE THREAD

**Issue by spacey-sooty** [SleipnirGroup/Choreo#507]
When running Debian stable with Choreo installed through the .deb I get a very slow (>30s) time to open Choreo. This is less than ideal

**Comment by calcmogul** [comment]
It varies between 2 and 5 seconds for me. I assume that's the Tauri backend server taking a while to start up, and the React frontend taking a while to load (likely more the latter). The build reports 1.1 MB of JavaScript (328 KB when gzip-compressed).

If we can't fix it, we could try adding a splashscreen: https://tauri.app/v1/guides/features/splashscreen/

**Comment by spacey-sooty** [comment]
Startup time seems better to me on main now for me
