### ISSUE TITLE
Infeasible trajectories with non-square module configurations

### ISSUE THREAD

**Issue by Nsl106** [SleipnirGroup/Choreo#549]
When setting the wheelbase and trackwidth to two different numbers it seems a lot of very simple paths fail to generate. As an example, here the wheelbase is 20" and the trackwidth is 17" and it fails to find a solution (same path obviously works with a normal configuration).
![image](https://github.com/user-attachments/assets/e1233e0b-5066-49a5-906a-3a7038503cce)

Here's the .chor file I was using for testing this. Github won't upload .chor files which is why it's .txt
[example.chor.txt](https://github.com/user-attachments/files/16500539/example.chor.txt)

**Comment by calcmogul** [comment]
I reproduced the issue with 2024.2.3, but it generates fine on main.

**Comment by calcmogul** [comment]
I finished bisecting this issue. It was fixed by #505.

**Comment by Nsl106** [comment]
I downloaded the version from [here](https://github.com/SleipnirGroup/Choreo/actions/runs/10406383532) and am having trouble building paths still. Is there something else I need to do to get the version with that fix?

**Comment by calcmogul** [comment]
Could you upload another .chor that reproduces the issue with the build on main?

**Comment by Nsl106** [comment]
So I downloaded the build from [here](https://github.com/SleipnirGroup/Choreo/actions/runs/10406383532) (it was the latest I could find) and ran the installer. Not sure if there's something else I need to be doing, but none of the paths here will generate.
[choreo.chor.txt](https://github.com/user-attachments/files/16639659/choreo.chor.txt)

**Comment by Nsl106** [comment]
Still using the build above, it appears that the 4AndCenter path in that file doesn't generate with both wheelbase and trackwidth set to 19.75".

**Comment by shueja** [comment]
This is a reported issue exacerbated by non-rectangular module configurations.

**Comment by bruingineer** [comment]
@Nsl106 are you seeing the same issues with `main` now?

**Comment by Nsl106** [comment]
It doesn't seem to have problems problem generating anymore. Though it still seems to overshoot stop points as mentioned [here](https://discord.com/channels/975739302933856277/1192238434341896294/1276617484614631424), but that's probably unrelated to this issue.
