### ISSUE TITLE
Fix infeasible path bug when "over rotating" start point

### ISSUE THREAD

**Issue by eBulosan** [SleipnirGroup/Choreo#555]
When rotating the start point with the hotkey one or more revolutions or entering a number into the text box with bigger than PI, it causes the trajectory to have odd generation, choosing rotate the longer way. With two or more revolutions with the hotkey (a bit more when entering it in with text) it shows an Infeasible Path Error, even for very simple paths (which were previously valid). 

These can be fixed by rotating the start point back with the hotkey to the original position (same number of revolutions), and by entering the theta manually (given its within the bounds of -PI to PI. 

https://github.com/user-attachments/assets/c14b4552-2f87-4de6-84fb-277ed3608e05

P.S. This is my first github issue; Hope I did good :)

**Comment by calcmogul** [comment]
Fixed by https://github.com/SleipnirGroup/Choreo/pull/505.
