### ISSUE TITLE
[choreo] Greatly reduced performance when running 2025 builds

### ISSUE THREAD

**Issue by spacey-sooty** [SleipnirGroup/Choreo#574]
When using the latest 2024 Choreo release most things responded to clicks pretty much instantly, on the 2025 version there is a noticeable delay (roughly 1-2 seconds mostly) when clicking things. This is worst on the configuration panel.
On Linux x86-64
![](https://cdn.discordapp.com/attachments/528555967827148801/1277475080703574026/image.png?ex=66cd4ce1&is=66cbfb61&hm=0d2cca75adcdeac2fe66bbf0a80bfb2978a8e2680057a47cea1e86b107bb8315&)
![](https://cdn.discordapp.com/attachments/528555967827148801/1277475080955367505/image.png?ex=66cd4ce1&is=66cbfb61&hm=4956939eec786eed3913db283f66d32acb9ad1009f5bcc328a8ff8a49342f5c6&)

**Comment by shueja** [comment]
Please confirm if this is still an issue on main.

**Comment by spacey-sooty** [comment]
Nope this is way better on main
