### ISSUE TITLE
[choreo] 2025 beta split trajectories view not displaying correctly

### ISSUE THREAD

**Issue by isaacngkh** [SleipnirGroup/Choreo#576]
In the split trajectories view, 1st, 2nd and 3rd trajectories are very similar in color.
![image](https://github.com/user-attachments/assets/e74beaa8-39d0-42e1-9300-5a327e1b1d41)

It is also not displaying correctly as number of splits increases
![image](https://github.com/user-attachments/assets/9cbe0f22-2806-47da-b0a6-e567630d7ba1)

**Comment by shueja** [comment]
First part proposed fix in #579 
Other part closed by #562
