### ISSUE TITLE
Automatically invalidate outdated trajectories after path is modified

### ISSUE THREAD

**Issue by jlbabilino** [SleipnirGroup/Choreo#60]
After a trajectory is generated then the user modifies the path, the user must be able to tell that the currently stored generated trajectory is no longer valid for the newly modified path.

**Comment by shueja-personal** [comment]
Should the trajectory disappear or turn into a grayed-out or dotted line?

**Comment by shueja** [comment]
Partially completed in 2024.2.0, otherwise superseded by #402
