### ISSUE TITLE
[choreo] Attempting to enter a heading into a pose waypoint after adjusting the heading by mouse fails

### ISSUE THREAD

**Issue by Gold856** [SleipnirGroup/Choreo#606]
Steps to reproduce:
1. Place down a pose waypoint.
2. Use the mouse cursor to change the waypoint heading.
3. Type in a new heading and hit enter.
4. Observe that the heading entry changes, but the heading in the trajectory does not.

Choreo version: f571654eb2f043b85c86264485eea35ad3ba4246

**Comment by shueja** [comment]
Known issue, fixed in #605
