### ISSUE TITLE
[choreo] Saving is unintuitive

### ISSUE THREAD

**Issue by Gold856** [SleipnirGroup/Choreo#610]
In order for everything to be saved, you need to click Save File and Save All Trajectories. The fact that it's two buttons is confusing, especially since it seems like everything is auto saved after that initial setup. One button that saves the .chor file along with the trajectories would be more intuitive.

**Comment by shueja** [comment]
The Save File button should save the .chor and the trajectories. Is this not your experience?

**Comment by Gold856** [comment]
The various updates to Choreo since then have made it so the Save File button does now save the .chor and trajectories.
