### ISSUE TITLE
[choreo] Saving a new project then reopening Choreo does not reopen the project

### ISSUE THREAD

**Issue by Gold856** [SleipnirGroup/Choreo#611]
Steps to reproduce:
1. Start a new Choreo project.
2. Save the Choreo project along with trajectories.
3. Close Choreo.
4. Open Choreo and observe that Choreo did not open the project you just saved.

Choreo version: f571654eb2f043b85c86264485eea35ad3ba4246

**Comment by shueja** [comment]
Fixed in #602
