### ISSUE TITLE
Allow a different robot configuration for each path

### ISSUE THREAD

**Issue by jlbabilino** [SleipnirGroup/Choreo#64]
Due to the current state of the trajectory generator, the physics parameters of the robot often need to be modified and tuned for each path. This is not ideal, but it's just the way it is right now. I know this from using HelixNavigator in the 2023 season.

If this feature is not added, users will be forced into creating a separate document file for each path, not utilizing the multi-path selection user interface within the app.

**Comment by shueja-personal** [comment]
How should this work with creating new paths and modifying overall physics parameters? If a user needs to tweak e.g. the robot mass because the design actually changed, do they modify a central main parameter list that the rest inherit from? What parameters are commonly fudged per-path?

**Comment by jlbabilino** [comment]
I'm trying to think of a way that isn't too complicated. One way would be like how it works in Unity, where it would pull the "main" configuration unless a value were overridden. Another option is to make each one separate, but add a button to copy one configuration to all the other paths.

The parameters commonly fudged are just max velocity and max torque.
