### ISSUE TITLE
Translational waypoint still having option to rotate

### ISSUE THREAD

**Issue by DanPeled** [SleipnirGroup/Choreo#690]
I don't know if this is intended or not, but the translational waypoint (which does not apply rotation), has the option to rotate it, which does not affect the path in the robot's target rotation

How I think it should be:
Just keep the same rotation of the previous waypoint and dont let the translational waypoint to be rotated

(This may be fixed in version 2025alpha, im using 2024.2.3)

**Comment by spacey-sooty** [comment]
Not true on main
