### ISSUE TITLE
Screen becomes blank after I pressed control + Z

### ISSUE THREAD

**Issue by DanPeled** [SleipnirGroup/Choreo#691]
I was writing a path and tried to undo a change and the screen became blank:
![image](https://github.com/user-attachments/assets/72347cbe-5d4e-4837-a14f-e610448de810)

**Comment by spacey-sooty** [comment]
Can you reproduce on 2025Alpha?

**Comment by DanPeled** [comment]
> Can you reproduce on 2025Alpha?

Tried, didnt manage to

**Comment by spacey-sooty** [comment]
Ok gonna close this then
