### ISSUE TITLE
[spec] Change `EventMarker` to use `Expr` for timestamp

### ISSUE THREAD

**Issue by oh-yes-0-fps** [SleipnirGroup/Choreo#738]

**Comment by shueja** [comment]
Which field needs to be Expr? The wait time on event markers is already an Expr.

**Comment by oh-yes-0-fps** [comment]
Yes, but changes need to be made accordingly in rust and choreolib

**Comment by shueja** [comment]
Made obsolete by design changes which are now targeted for beta 2
