### ISSUE TITLE
White bar at bottom of screen on MacOS fullscreen

### ISSUE THREAD

**Issue by JoshuaAN** [SleipnirGroup/Choreo#78]
![Screen_Shot_2023-07-23_at_7 15 50_PM](https://github.com/SleipnirGroup/Choreo/assets/45806130/9c25e234-6bf9-40d5-b469-c9f3d697be8f)

**Comment by jlbabilino** [comment]
Can you check and see if this is still happening? It doesn't happen on my mac.
