### ISSUE TITLE
Under some circumstances, a flipped Point At constraint causes path to be infeasible

### ISSUE THREAD

**Issue by Gold856** [SleipnirGroup/Choreo#806]
[choreo-diagnostics-N1kASHLw.zip](https://github.com/user-attachments/files/17230797/choreo-diagnostics-N1kASHLw.zip)

Attempting to generate the trajectory fails, even though it looks like it should be fine. The slightest adjustment of the path causes it to be feasible. This includes:
* Removing other waypoints that shouldn't make a difference in the constrained segment due to stop points
* Changing the wheel size to 3 in
* Unflipping the constraint
* Changing dt to 0.02

Choreo version: 2025 beta 1

**Comment by bruingineer** [comment]
I just tried this file with #820 and #821 and it generates
