### ISSUE TITLE
A path that ends with a translation waypoint can cause infeasibility

### ISSUE THREAD

**Issue by Gold856** [SleipnirGroup/Choreo#807]
[choreo-diagnostics-XLvaLMdD.zip](https://github.com/user-attachments/files/17231299/choreo-diagnostics-XLvaLMdD.zip)

This trajectory should be super feasible, yet it fails for no apparent reason. Changing the wheel size to 3 in or changing the last waypoint to be a pose waypoint makes the trajectory feasible. This might be the underlying issue of #806.

Choreo version: 2025 beta 1

**Comment by shueja** [comment]
It looks like the issue was in the control interval guessing between point 3 and 4, which was 13 samples. Changing it to 14 samples also works.

**Comment by bruingineer** [comment]
I just tried this file with #820 and #821 and it generates
