### ISSUE TITLE
Windows undefined symbol error when building with `cargo build`

### ISSUE THREAD

**Issue by jlbabilino** [SleipnirGroup/Choreo#84]
<img width="385" alt="Screenshot 2023-07-24 at 23 24 42" src="https://github.com/SleipnirGroup/Choreo/assets/28580376/30cda848-3753-4a29-a577-82f433316cd3">

This can be avoided by using `cargo build --release` or `npm run tauri dev -- --release`.

**Comment by calcmogul** [comment]
OBE by #326.
