### ISSUE TITLE
Trajectory no longer generates after beta 2

### ISSUE THREAD

**Issue by Gold856** [SleipnirGroup/Choreo#840]
[choreo-diagnostics-r2r65p3u.zip](https://github.com/user-attachments/files/17267216/choreo-diagnostics-r2r65p3u.zip)

The fix to #807 (f3c2a19fea7701f6afa6485e4c7eeebe35305f0d) caused Choreo to fail to generate this trajectory. It generated fine in beta 2, but doesn't after that commit.

**Comment by spacey-sooty** [comment]
That path generates fine on main.

**Comment by Gold856** [comment]
I wouldn't say it generates "fine", since there's two 360s in the path, but this issue can be closed, since it's basically a duplicate of #841.
