### ISSUE TITLE
Choreo struggles to generate paths on the red alliance

### ISSUE THREAD

**Issue by Gold856** [SleipnirGroup/Choreo#841]
[choreo-diagnostics-L0jt2wS1.zip](https://github.com/user-attachments/files/17267278/choreo-diagnostics-L0jt2wS1.zip)

This path does two 360s which seems not optimal. The commit before https://github.com/SleipnirGroup/Choreo/commit/f3c2a19fea7701f6afa6485e4c7eeebe35305f0d generated a much better path:
[choreo-diagnostics-SMQUqTpZ.zip](https://github.com/user-attachments/files/17267283/choreo-diagnostics-SMQUqTpZ.zip)

**Comment by Gold856** [comment]
I think Choreo might have an issue with generating trajectories on the red alliance. Here's a version with a red and blue alliance path. They should be very similar, yet the red alliance version takes longer to generate and does 1.5 rotations at the start.
[choreo-diagnostics-Lbngs3xO.zip](https://github.com/user-attachments/files/17267617/choreo-diagnostics-Lbngs3xO.zip)

**Comment by spacey-sooty** [comment]
This is a regression from beta 2.

**Comment by bruingineer** [comment]
made similar behaviour on the blue side trajectory when waypoint 2 has -pi rad heading:
![image](https://github.com/user-attachments/assets/e89bb36a-3d42-4b6c-a501-65ef511161e5)

note: the red behaviour goes away if waypoint 2's heading is changed from -pi rad to pi rad.
