### ISSUE TITLE
C++ `AutoFactory` constructor documentation refers to non-existent `Choreo::CreateAutoFactory()`

### ISSUE THREAD

**Issue by bhall-ctre** [SleipnirGroup/Choreo#905]
The documentation for the [`AutoFactory` constructor](https://github.com/SleipnirGroup/Choreo/blob/main/choreolib/src/main/native/include/choreo/auto/AutoFactory.h#L64-L73) only points to a `Choreo::CreateAutoFactory()` function, which exists in [Java](https://github.com/SleipnirGroup/Choreo/blob/main/choreolib/src/main/java/choreo/Choreo.java#L313) but not [C++](https://github.com/SleipnirGroup/Choreo/blob/main/choreolib/src/main/native/include/choreo/Choreo.h#L24).

It looks like the class comment is also out-of-date with recent changes to Choreo (such as AutoLoop -> AutoRoutine).

**Comment by calcmogul** [comment]
Turns out those files don't even get compiled, and the Java tests that would have caught that were never ported to C++ (C++ has almost no tests). We clearly have some process improvements to do.
