### ISSUE TITLE
Last Trajectory Sample Not Mirrored.

### ISSUE THREAD

**Issue by IShaLinI** [SleipnirGroup/Choreo#954]
Ghost is the output from sample.getPose() inside of my choreoController.

https://github.com/user-attachments/assets/4ffe9bfb-5289-4e02-adfb-e4acbcc1540f
![image](https://github.com/user-attachments/assets/f6e5668e-7859-407b-8bad-6b02a952dc65)
![image](https://github.com/user-attachments/assets/db237bb0-e5c4-400a-8ff6-b45bc5c6d3dd)

**Comment by shueja** [comment]
Fixed on main, but definitely was an issue on 2025.0.0-beta-6.
