### ISSUE TITLE
Math expression parsing for numerical entry text boxes 

### ISSUE THREAD

**Issue by jlbabilino** [SleipnirGroup/Choreo#96]
Example: typing `2 + 3` into a number text box should enter the value of `5`.

Basic mathematical syntax, functions, and constants should be supported. `(sin(pi/2)+1*2)^2` will result in `9`.

An example implementation of this is in [HelixNavigator](https://github.com/TripleHelixProgramming/HelixNavigator/blob/master/app/src/main/java/org/team2363/lib/math/ExpressionParser.java).

**Comment by jlmcmchl** [comment]
Is this intended to support limits? ie sin(0)/0 is undefined on its own, but lim x->0 sin(x)/x is 1.

**Comment by jlbabilino** [comment]
Is there a specific situation you need that kind of functionality?

**Comment by jlbabilino** [comment]
I think [mathjs](https://mathjs.org/index.html) is the perfect candidate for this.
