### ISSUE TITLE
Numeric input text boxes don't update

### ISSUE THREAD

**Issue by jlbabilino** [SleipnirGroup/Choreo#97]
https://github.com/SleipnirGroup/Choreo/assets/28580376/8281473e-ac7c-433f-b29e-3bd6b84d5564

**Comment by shueja-personal** [comment]
Closed by #98

**Comment by jlbabilino** [comment]
#98 did not fully fix the problem.

**Comment by jlbabilino** [comment]
If a certain numerical entry box is in focus (clicked on, text is selected), then a different waypoint is selected, all the other text boxes update, but the one in focus does not update.
